version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123
    volumes: 
      - cache:/data
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: neineihello/api:v1
    depends_on:
      - redis
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123
    command: npm run dev
    volumes: 
      - ./api:/app

volumes:
  cache:
  
  
