version: '3.8'
services:
  redis:
    container_name: redis_1
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6377:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 456

  api:
    container_name: api_prod
    image: neineihello/new
    depends_on:
      - redis
    ports:
      - 3003:3000
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 456
    command: npm start
  
